spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: uPlik6C8TNcGAcDTzlpwjNQYTgcbwrIy
            client-secret: xHQJF5cx5SSjOZ_HWRSMpUKrh1kc4b5qyEwP1aV37CmJzOznsdfEmVz8RIPY-RGt
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-3z7jadf9.us.auth0.com/